name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t kvshuser/todolist:${{ github.sha }} .
          echo ${{ secrets.SPRINTBOX_ACCESS_TOKEN }} | docker login -u kvshuser --password-stdin
          docker push kvshuser/todoliste:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            docker pull kvshuser/todolist:${{ github.sha }}
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp \
              -e AUTH_SERVER_URL=${{ secrets.AUTH_SERVER_URL }} \
              -p 80:80 \
              kvshuser/todolist:${{ github.sha }}
